# Generated by Django 5.0 on 2025-03-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
